# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker
spring:
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: https://keycloak.createyourevent.space/realms/jhipster
        registration:
          oidc:
            client-id: jhipster-registry
            client-secret: 8gwv7UlagY4sXWYOgZNY5cGfo08aesgZ
            scope: openid,profile,email
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: https://registry.createyourevent.space/eureka/