# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker
spring:
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: https://keycloak.createyourevent.space/realms/jhipster
        registration:
          oidc:
            client-id: web_app
            client-secret: 0CMtGDXKuTGC7d89brAPw8I5YVgzRbOS
            scope: openid,profile,email
eureka:
  client:
    service-url:
      defaultZone: https://registry.createyourevent.space/eureka/
